<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <?php
        if ($route === null || $route === 'home') {
            require 'home.phtml';
        } else if ($route === 'inscription') {
            require 'register.phtml';
        } else if ($route === 'connexion') {
            require 'login.phtml';
        }
    ?>
</body>
</html>