
<form action="logic/register.php" method="POST">
    <label for="first_name">Prénom :</label><br>
    <input type="text" name="first_name" id="first_name" required><br><br>
    
    <label for="last_name">Nom :</label><br>
    <input type="text" name="last_name" id="last_name" required><br><br>
    
    <label for="email">Email :</label><br>
    <input type="email" name="email" id="email" required><br><br>
    
    <label for="password">Mot de passe :</label><br>
    <input type="password" name="password" id="password" required><br><br>
        
    <button type="submit">Soumettre</button>
</form>
