<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <!-- Votre formulaire ici -->
    <form method="post" action="controllers/user-form.php">
        <fieldset>
            <label for="email">
                Email : 
            </label>
            <input type="text" name="email" id="emailId"/>
            <br>
            <label for="password">
                Password :
            </label>
            <input type="text" name="password" id="passwordId"/>
            <br>
            <label for="confPassword">
                Confirm password :
            </label>
            <input type="text" name="confPassword" id="confPasswordId"/>
        </fieldset>
        <fieldset>
            <label for="newsletterId"><br>S'inscrire à la newsletter ?</label>
            <input type="checkbox" id="newsletterId" name="newsletter" value="oui"/>
        </fieldset>
        <fieldset>
        <br>
        <button type="submit">Envoyer</button>
        </fieldset>
    </form>
    
</main>