<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Mini Blog</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="index.php">Accueil</a></li>
            <li><a href="index.php?route=a-propos">À propos</a></li>
            <li><a href="index.php?route=contact">Contact</a></li>
            <li><a href="index.php?route=categorie&categorie=dev-back">Dev Back</a></li>
            <li><a href="index.php?route=categorie&categorie=dev-front">Dev Front</a></li>
            <li><a href="index.php?route=article&article=i-love-php">I love PHP</a></li>
            <li><a href="index.php?route=article&article=i-love-js">I love JS</a></li>
        </ul>
    </nav>

    <main>
    </main>
</body>
</html>